{
 "title": "MPDV Services - Service details",
 "description": "Overview of the details of called services (number, duration, aborts, number of records) ",
 "tags": [
  "MPDV",
  "detail",
  "services"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Instance",
    "query": "label_values(wsp_services_duration_running_seconds_duration_sum{}, job)"
   },
   {
    "name": "service_domain",
    "label": "Service Domain",
    "query": "label_values(wsp_services_duration_running_seconds_duration_sum{job=\"$job\"}, service_domain)"
   },
   {
    "name": "service_function",
    "label": "Service Function",
    "query": "label_values(wsp_services_duration_running_seconds_duration_sum{job=\"$job\", service_domain=~\"$service_domain\"}, service_function)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of service calls",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(sum by (job, service_domain, service_function)(wsp_services_calls_total{job=\"$job\",service_domain=~\"$service_domain\",service_function=~\"$service_function\"}) - sum by (job, service_domain, service_function)(wsp_services_calls_total{job=\"$job\",service_domain=~\"$service_domain\",service_function=~\"$service_function\"} offset 5m))",
     "legendFormat": "{{service_domain}}.{{service_function}}",
     "rawSql": "SELECT\n  $__timeEpoch(<time_column>),\n  <value column> as value,\n  <series name column> as metric\nFROM\n  <table name>\nWHERE\n  $__timeFilter(time_column)\nORDER BY\n  <time_column> ASC"
    }
   ]
  },
  {
   "title": "Duration of service calls",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "abs(sum by (job, service_domain, service_function)(wsp_services_duration_total_seconds_sum{job=\"$job\",service_domain=~\"$service_domain\",service_function=~\"$service_function\"}) - sum by (job, service_domain, service_function)(wsp_services_duration_total_seconds_sum{job=\"$job\",service_domain=~\"$service_domain\",service_function=~\"$service_function\"} offset 5m))",
     "legendFormat": "{{service_domain}}.{{service_function}}",
     "rawSql": "SELECT\n  $__timeEpoch(<time_column>),\n  <value column> as value,\n  <series name column> as metric\nFROM\n  <table name>\nWHERE\n  $__timeFilter(time_column)\nORDER BY\n  <time_column> ASC"
    }
   ]
  },
  {
   "title": "Number of service interruptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(sum by (job, service_domain, service_function)(wsp_services_errors_total{job=\"$job\",service_domain=~\"$service_domain\",service_function=~\"$service_function\"}) - sum by (job, service_domain, service_function)(wsp_services_errors_total{job=\"$job\",service_domain=~\"$service_domain\",service_function=~\"$service_function\"} offset 5m))",
     "legendFormat": "{{service_domain}}.{{service_function}}",
     "rawSql": "SELECT\n  $__timeEpoch(<time_column>),\n  <value column> as value,\n  <series name column> as metric\nFROM\n  <table name>\nWHERE\n  $__timeFilter(time_column)\nORDER BY\n  <time_column> ASC"
    }
   ]
  },
  {
   "title": "Number of records (per result set)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(sum by (job, service_domain, service_function, resultset_id)(wsp_services_returned_records_total_sum{job=\"$job\",service_domain=~\"$service_domain\",service_function=~\"$service_function\",resultset_id!=\"_inexistent_\"}) - sum by (job, service_domain, service_function, resultset_id)(wsp_services_returned_records_total_sum{job=\"$job\",service_domain=~\"$service_domain\",service_function=~\"$service_function\",resultset_id!=\"_inexistent_\"} offset 5m))",
     "legendFormat": "{{service_domain}}.{{service_function}} - {{resultset_id}}",
     "rawSql": "SELECT\n  $__timeEpoch(<time_column>),\n  <value column> as value,\n  <series name column> as metric\nFROM\n  <table name>\nWHERE\n  $__timeFilter(time_column)\nORDER BY\n  <time_column> ASC"
    }
   ]
  }
 ]
}