apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-rollouts
    targetRevision: 2.40.0
    helm:
      valueFiles:
      - $values/values/argo-rollouts.yaml
  - repoURL: 'https://github.com/samuelamaralls/app-of-apps-infra.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
