apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: 1.18.2
    helm:
      valueFiles:
      - $values/values/cert-manager.yaml
  - repoURL: 'https://github.com/samuelamaralls/app-of-apps-infra.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc