apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.gitlab.io/'
    chart: gitlab-runner
    targetRevision: 0.79.0
    helm:
      valueFiles:
      - $values/values/gitlab-runner.yaml
  - repoURL: 'https://github.com/samuelamaralls/app-of-apps-infra-helm.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: gitlab-runner
    server: https://kubernetes.default.svc
