apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki
    targetRevision: 3.0.1
    helm:
      valueFiles:
      - $values/values/loki.yaml
  - repoURL: 'https://github.com/samuelamaralls/app-of-apps-infra.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
